{{-- Pagination Component --}}
<div class="row mt-4">
    <div class="col-12">
        <div class="pagination-wrapper text-center">
            <div class="custom-pagination">
                <button class="pagination-btn prev-btn" onclick="prevPage()" disabled>
                    <i class="bi bi-chevron-left"></i>
                    <span>Précédent</span>
                </button>
                <div class="pagination-numbers" id="paginationNumbers">
                    {{-- Page numbers will be generated by JavaScript --}}
                </div>
                <button class="pagination-btn next-btn" onclick="nextPage()">
                    <span>Suivant</span>
                    <i class="bi bi-chevron-right"></i>
                </button>
            </div>
        </div>
    </div>
</div>